# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class IpsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, sha1: str=None, file_name: str=None):  # noqa: E501
        """IpsBody - a model defined in Swagger

        :param sha1: The sha1 of this IpsBody.  # noqa: E501
        :type sha1: str
        :param file_name: The file_name of this IpsBody.  # noqa: E501
        :type file_name: str
        """
        self.swagger_types = {
            'sha1': str,
            'file_name': str
        }

        self.attribute_map = {
            'sha1': 'sha1',
            'file_name': 'fileName'
        }
        self._sha1 = sha1
        self._file_name = file_name

    @classmethod
    def from_dict(cls, dikt) -> 'IpsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ips_body of this IpsBody.  # noqa: E501
        :rtype: IpsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sha1(self) -> str:
        """Gets the sha1 of this IpsBody.


        :return: The sha1 of this IpsBody.
        :rtype: str
        """
        return self._sha1

    @sha1.setter
    def sha1(self, sha1: str):
        """Sets the sha1 of this IpsBody.


        :param sha1: The sha1 of this IpsBody.
        :type sha1: str
        """

        self._sha1 = sha1

    @property
    def file_name(self) -> str:
        """Gets the file_name of this IpsBody.


        :return: The file_name of this IpsBody.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this IpsBody.


        :param file_name: The file_name of this IpsBody.
        :type file_name: str
        """

        self._file_name = file_name
